apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name:  nginx-configmap
          readOnly: true

      
      volumes:
      - name: nginx-configmap
        configMap:
          name: nginx
          items:
            - key: nginx.conf
              path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    server {
          listen 80;
          listen [::]:80;

          access_log /var/log/nginx/reverse-access.log;
          error_log /var/log/nginx/reverse-error.log;
        
          location / {
              proxy_pass http://app-mvc-using-react:3000;
          }
    }
